version: '3.7'

services:
  polystore_ui:
    build: .
    environment:
      API_HOST: adsadad
      API_PORT: 8081
    container_name: polystore-ui
    ports:
      - 4200:4200
    restart: always
    hostname: polystore-ui
  polystoredb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: polystore-mongo
    hostname: polystore-api-db
    ports:
      - 27017:27017
  MariaDBDWH:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  MariaDBFinesse:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306
  MongoDB:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
