version: '3.7'

services:
  polystore_ui:
    build: .
    environment:
      API_HOST: localhost
      API_PORT: 8081
    container_name: polystore-ui
    ports:
      - 4200:4200
    restart: always
    hostname: polystore-ui
  polystoredb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: polystore-mongo
    hostname: polystore-api-db
    ports:
      - 27017:27017
