version: '3.3'

services:
  polystore:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    #image: clms/typhon-polystore-api:latest
    hostname: polystore.api
    container_name: typhonml.polystore.service
    ports:
      - "8080:8080"
    volumes:
     - "./models:/models"
    depends_on:
      - mongostore
  mongostore:
    image: mongo:latest
    hostname: polystore.api.db
    container_name: polystore.mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    #volumes:
    # - "./data:/data/db"
  mariadbtest:
    image: mariadb:latest
    hostname: test.mariadb
    container_name: test.mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
