version: '3.3'

services:
  polystore:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    hostname: polystore.api
    container_name: typhonml.polystore.service
    ports:
      - "8080:8080"